# cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argooperator-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: argooperator
  namespace: argo
roleRef:
  kind: ClusterRole
  name: argooperator-clusterrole
  apiGroup: rbac.authorization.k8s.io
