# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: argooperator
#   namespace: argo
# secrets:
# - name: argooperator-sa

# service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argooperator
  namespace: argo
secrets:
- name: argooperator-sa
